anhdt/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});
Route::get('hello-world','HelloWorldController@show');
Route::resource('users','UsersController');

anhdt/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
	protected $table = 'users';
    protected $fillable = [
        'mail_address', 'password', 'name', 'address', 'phone',
    ];
}

anhdt/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

anhdt/app/Http/Controllers/HelloWorldController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HelloWorldController extends Controller
{
    public function show() {
    	return view('hello_world/show');
    }
}

anhdt/app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CreateUserRequest;
use App\Models\User;
use DB;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataUsers = User::orderBy('mail_address', 'ASC')->paginate(20);
        return view('index', ['users' => $dataUsers]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('newuser');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $users = $request->all();
        $users['password'] = bcrypt($request->password);
        User::create($users);
        return redirect()->route('users.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

anhdt/resources/views/hello_world/show.blade.php
<?php
    echo 'Nội dung tùy ý';
?>

anhdt/resources/views/index.blade.php
<html>
<head>
    <meta charset="utf-8">
    <title>Danh sách users</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
</head>
<body>
    <div class="container">
        <table class="table table-bordered" style="margin: center">
            <thead style="text-align: center">
                <tr>
                    <th>STT</th>
                    <th>Địa chỉ email</th>
                    <th>Tên</th>
                    <th>Địa chỉ</th>
                    <th>Số điện thoại</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = ($users->currentpage()-1)*$users->perpage() +1; ?>
                @foreach($users as $user)
                    <tr>
                        <th>{{ $i++ }}</th>
                        <th>{{ $user-> mail_address }}</th>
                        <th>{{ $user->name }}</th>
                        <th>{{ $user-> address }}</th>
                        <th>{{ $user-> phone }}</th>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{ $users->links() }}
        <a href="{{ route('users.create') }}" class="button">Thêm mới User</a>
    </div>
</body>
</html>

anhdt/resources/views/newuser.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Thêm mới</title>
    <link rel="stylesheet" type="" "text/css" href="{{ asset('css/app.css') }}">
    <style type="text/css">
        .error{
            color: red;
        }
        .border{
            border:solid 1px red;
        }
    </style>
    <meta charset="utf-8">

</head>
<body>
    <div style="margin-top: 100px; margin-left: 350px; margin-right: 350px">
        <form method="POST" action="{{ route('users.store') }}">
            <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
            <div class="form-group">
                <label class="@if ($errors->has('mail_address')) {{'error'}} @endif">mail address</label>
                <input type="email" class="form-control @if ($errors->has('mail_address')) {{'border'}} @endif" name="mail_address" placeholder="Enter email">
                <label class="error">{{ $errors->first('mail_address') }}</label>
            </div>
            <div class="form-group">
                <label class="@if ($errors->has('password')) {{'error'}} @endif">Password</label>
                <input type="password" class="form-control @if ($errors->has('password')) {{'border'}} @endif" name="password" placeholder="Enter Password">
                <label class="error">{{ $errors->first('password') }}</label>
            </div>
            <div class="form-group">
                <label class="@if ($errors->has('password_confirmation')) {{'error'}} @endif">Password Comfirm</label>
                <input type="password" class="form-control @if ($errors->has('password_confirmation')) {{'border'}} @endif" name="password_confirmation" placeholder="Enter Password Comfirm">
                <label class="error">{{ $errors->first('password_confirmation') }}</label>
            </div>
            <div class="form-group">
                <label class="@if ($errors->has('name')) {{'error'}} @endif">Name</label>
                <input type="text" class="form-control @if ($errors->has('name')) {{'border'}} @endif" name="name" placeholder="Enter Name">
                <label class="error">{{ $errors->first('name') }}</label>
            </div>
            <div class="form-group">
                <label class="@if ($errors->has('address')) {{'error'}} @endif">Address</label>
                <input type="text" class="form-control @if ($errors->has('address')) {{'border'}} @endif" name="address" placeholder="Enter Address">
                <label class="error">{{ $errors->first('address') }}</label>
            </div>
            <div class="form-group">
                <label class="@if ($errors->has('phone')) {{'error'}} @endif">Phone</label>
                <input type="text" class="form-control @if ($errors->has('phone')) {{'border'}} @endif" name="phone" placeholder="Enter Phone">
                <label class="error">{{ $errors->first('phone') }}</label>
            </div>
            <button type="submit" class="btn btn-primary" name="create_action">Register</button>
        </form>
    </div>
</body>
</html>